version: '3.7'

services:
  web:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    command: ["-nginx.scrape-uri=http://web/status"]
    ports:
      - "9113:9113"
    depends_on:
      - web
    networks:
      - webnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webnet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - webnet

networks:
  webnet:
